FROM python:3.7

LABEL name=dummy-dpsim
LABEL version=0.1
LABEL description='dummy simulator'
LABEL maintainer_email='acs-software@eonerc.rwth-aachen.de'

ADD . /se-service
WORKDIR /se-service

RUN pip3 install paho-mqtt

CMD ["sh", "-c", "sleep 5 &&  python ./examples/dummy_simulator.py"]